### ISSUE TITLE
Standard Duration configuration for Data Prepper 

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#1079]
**Is your feature request related to a problem? Please describe.**
Many processors have configuration options available for specifying durations (for example, the Aggregate Processor `group_duration` and the Service Map `window_duration`. This can lead to a worse user experience, as the user does not immediately know the unit of the duration, and they have to calculate based on that unit depending on the value they want to provide.

**Describe the solution you'd like**
A standard approach to Duration configurations in Data Prepper. This would include support for two separate types of Duration strings

1. Simple strings to specify Durations in milliseconds, seconds, minutes, hours, or days. This will be easier for some to use as it is simple to read and easier to create without knowledge of ISO 8601
Here are some examples of the units we will support with this approach

```
"100ms" // 100 milliseconds
"60s" // 60 seconds
"15min" // 15 minutes
"2hr" // 2 hours
"3day" // 3 days
```
2. ISO_8601 notation (Ex: `P3DT4H59M` or `PT2H30M`)

The validation and building of these durations should be done within `data-prepper-core/data-prepper-api`, if possible. For example, a configuration for `group_duration` could look like the following:

```
@ValidDurationString
private String durationString;

and then build the actual duration with an API call of 

Duration duration = getDurationFromString(durationString);
```

**Describe alternatives you've considered (Optional)**
Keep things the way they are now and only support one unit of time for configurations, while mentioning the unit they use (ex: `group_duration_seconds`)

**Additional context**

**Comment by dlvenable** [comment]
I think we can reduce the "simple" durations to just milliseconds ("ms") and seconds ("s"). I think it becomes too confusing if we expand beyond that because there are so many different options... "3 day", "3 d", "3 days". Seconds and milliseconds will cover most use-cases and ISO 8601 durations support all use-cases.

Also, I think the "simple" durations should not be combined. They are just seconds or milliseconds - no "10 s 500 ms".

**Comment by asifsmohammed** [comment]
I like the 2nd solution since it's easy to validate and no need to write custom parser to parse the strings. It might look something like this
```
long group_duration_seconds = Duration.parse("PT2H30M").getSeconds();
```

**Comment by graytaylor0** [comment]
@asifsmohammed The proposal is to actually support both the ISO 8601 notation and the simple strings. I think that most people will probably prefer to use the simple strings actually.

**Comment by dlvenable** [comment]
Supporting simple strings could help with consistency for all durations. We could use this for values like `request_timeout`. I can't imagine anybody wanting to use ISO 8601 time here. But, it could be valuable to specify `10s` rather than `10000` (for milliseconds).

**Comment by graytaylor0** [comment]
@dlvenable what are your thoughts on the implementation I outline above? Is it relatively easy for us to create custom validation annotations and add them to our Jakarta validation?

**Comment by dlvenable** [comment]
@graytaylor0 , I think this is a great thing to add to Data Prepper. I think the name could be simplified - maybe `@Duration`, `@DurationValue`, or `@DurationString`.

It is relatively easy to implement. You'd create an `@Constraint` annotation and a `ConstraintValidator`.

Something like:
```
@Constraint(validatedBy = DurationValidator.class)
public @interface Duration {
  ...
}
```

While the `Duration` annotation must exist in `data-prepper-api`, I'd like `DurationValidator` defined in `data-prepper-core`. I know this can be done somehow because the default validators (`@NotNull`, `@Min`, etc.) do this. Even if we can't find how to do that, the worst-case scenario we have it in `data-prepper-api`.

**Comment by dlvenable** [comment]
@graytaylor0 , It may be even better to rely on Jackson for validating the `Duration`. Data Prepper could have a custom deserializer for `Duration` types. It would support parsing either of these formats. If the value is invalid, it will throw an exception which will validate that it is correct. This would really simplify the configuration classes because they just look like:

```
private Duration groupDuration;

public Duration getGroupDuration() {
  return groupDuration;
}
```
