### ISSUE TITLE
Does otel-trace-group-prepper will be obsolote in 1.4? Is it compatible with the "OTel Trace Raw Processor"

### ISSUE THREAD

**Issue by elvince** [opensearch-project/data-prepper#1673]
**Describe the bug**
As of now (mandatory in 1.4), we should use the OTel Trace Raw Processor and not anymore the otel_trace_raw_prepper.
As the otel-trace-group-prepper seems to be using the output of otel_trace_raw_prepper. 
Is it still relevant for “Otel Trace Raw Processor” ? Are they compatible or will it be obsolete as otel_trace_raw_prepper in dataprepper 1.4?

We are building the OTEL Pipeline and follow the recommandation of the documentation by using “Otel Trace Raw Processor”.

We are interested in the prepper "otel-trace-group-prepper" as we have some element that will process  in a RabbitMQ queue. That's means when the trace will to dataprepper, we will be out of the window. As per our understanding this prepper will help to fill the gap by finding the information already set in opensearch to enrich the current set of data before import.

Thanks for the help in clarification,

**Comment by dlvenable** [comment]
@elvince ,

In Data Prepper 1.4, we added an alternative mechanism for processing traces and we plan to remove the old approach in 2.0. The new approach uses Data Prepper's event model. It is different because each span is put into the buffer as its own item. In the previous approach (prior to 1.4 and sill available), each item in the buffer was the entire OTel `ExportTraceServiceRequest`. You can read some more about the motivation in #1158. One advantage to this approach is that you can add custom processors after the `otel_trace_source` to manipulate each span.

To prepare for Data Prepper 2.0 you should migrate to using both `otel_trace_raw` and `otel_trace_group`. These plugins are compatible with each. In order to use these, you must also configure your `otel_trace_source` with the `record_type: event` value.

In Data Prepper 2.0, we will remove both `otel_trace_raw_prepper` and `otel_trace_group_prepper`.

> We are interested in the prepper "otel-trace-group-prepper" as we have some element that will process in a RabbitMQ queue. That's means when the trace will to dataprepper, we will be out of the window.

Is there something that the `otel_trace_group` processor is lacking that you need?

**Comment by elvince** [comment]
@dlvenable 
Thanks for the anwser and for the vision of where you go with this.

I didn't see that you already put the otel_trace_group processor in the plugins, my bad. 
I should be all set now as I will put the 2 new processors in my pipeline.

Thanks for the clarification
