### ISSUE TITLE
Emit Metrics for ACM and AWS CloudMap related calls

### ISSUE THREAD

**Issue by dinujoh** [opensearch-project/data-prepper#2087]
**Is your feature request related to a problem? Please describe.**
It would be nice to have metrics for ACM and AWS CloudMap related api calls to monitor the success, latency and error for the calls that can be used to create alarm.

**Describe the solution you'd like**
With the AWS SDK for Java 2.x, you can collect metrics about the service clients in your application, analyze the output in Amazon CloudWatch, and then act on it.
https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/metrics.html

AWS SDK v2 doesn't support custom publisher yet:
https://github.com/aws/aws-sdk-java-v2/issues/3311#issuecomment-1194487912

**Describe alternatives you've considered (Optional)**
Instrument the api calls explicitly when the API calls to ACM and AWS CloudMap are made using existing Metrics collector.

**Comment by oeyh** [comment]
Discussed offline about the paths to move forward, a brief summary:

### Proposed method
Implements `MetricPublisher` interface in AWS SDK that adapts to the current Micrometer setup in Data Prepper. (See the default CloudWatch publisher [CloudWatchMetricPublisher](https://github.com/aws/aws-sdk-java-v2/blob/master/metric-publishers/cloudwatch-metric-publisher/src/main/java/software/amazon/awssdk/metrics/publishers/cloudwatch/CloudWatchMetricPublisher.java) for reference)

```
public class MicrometerMetricPublisher implements MetricPublisher
```

Then we can use it to configure AWS SDK clients to emit metrics whenever the clients are sending requests:

```
MicrometerMetricPublisher micrometerMetricPublisher = MicrometerMetricPublisher.create()
ACMClient acmClient = ACMClient.builder()
                           .overrideConfiguration(o -> o.addMetricPublisher(micrometerMetricPublisher))
                           .build();
```

`MicrometerMetricPublisher` can add custom tags/dimensions to AWS SDK generated metrics and send them to Micrometer metric registries that we have today (Prometheus, AWS CloudWatch, or EMF registries).

Considering the use case of aggregating AWS SDK metrics across AWS services, those metrics can have qualified names in the format of: 
```
aws.sdk.${metricName}
```
It uses the actual metric name `metricName` defined in SDK prefixed with constant `aws.sdk`. We can have a new class rather than `PluginMetrics` to model those SDK metrics.

Pros:
- Utilizes SDK generated metrics that may be difficult to get manually in Data Prepper
- Consistent metrics collection throughout Data Prepper and the ability to maintain the support for Prometheus, CloudWatch, and EMF.

Cons:
- Nontrivial development effort


### Alternative methods
#### Utilize `CloudWatchMetricPublisher` from SDK to publish SDK metrics directly to CloudWatch

Pros:
- Low development effort
- Can be readily used in CloudWatch for service level monitoring

Cons:
- Inconsistent with existing Micrometer setup
- Support only CloudWatch for publishing


#### Manually create custom metrics like other plugin metrics we have today.

Pros:
- Consistent metrics collection throughout Data Prepper and the ability to maintain the support for Prometheus, CloudWatch, and EMF.

Cons:
- Some metrics that SDK provides may be difficult to reproduce in this way

**Comment by dlvenable** [comment]
One additional comment I'd add is that we take the same tags/dimensions provided by the AWS SDK and apply them as Micrometer tags. In this way we get the same dimensions that they provide (e.g. ServiceName and Endpoint).
