### ISSUE TITLE
[BUG] JacksonMetric should not flatten attributes field

### ISSUE THREAD

**Issue by kkondaka** [opensearch-project/data-prepper#2146]
**Describe the bug**
Currently JacksonMetric flattens `attributes` when `toJsonString()` is invoked (see https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-api/src/main/java/org/opensearch/dataprepper/model/metric/JacksonMetric.java#L41). This means all the keys in the `attributes` field are moved to the Jackson Metric instead of keeping them in the `attributes`. OTEL format specifies attributes map as one of the fields. For compatibility with other OTEL metric formats, this `attributes` field should be left as is (not get flattened)

**To Reproduce**

**Expected behavior**
Expected behavior is that `attributes` field is kept as is without flattening it.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]

**Additional context**

**Comment by dlvenable** [comment]
@kmssap , Can you provide some insight into why the metrics are currently flattening the attributes?

**Comment by kkondaka** [comment]
@kaimst @KarstenSchnitter What do you think about this? Would changing this break any of your deployments?

**Comment by kmssap** [comment]
Hello @kkondaka and @dlvenable, I believe this was a design decision that we originally made in order to avoid having to deal with arrays in OpenSearch and thereby make it easier to address individual data points with regards to visualization. But it's certainly something that could be changed. Maybe having a feature flag for this would make sense ? Or abandon the record-per-data point approach altogether ? Perhaps @KarstenSchnitter can chime in here ?

**Comment by kkondaka** [comment]
Thanks @kmssap, we will keep the current behavior as default behavior and add support to disable the flattening of attributes.

**Comment by dlvenable** [comment]
@kkondaka submitted #2163 which adds a new flag to the `otel_metrics_processor`. By default it will retain the current behavior.

The other new metrics processors are using the un-flattened approach. We can always add the ability to flat those in the future if there is a concrete request.
