### ISSUE TITLE
[BUG] OTEL Logs source created has observed timestamp of 1970

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/data-prepper#2268]
**Describe the bug**
Observed Timestamp is set as 1970 01 01, should this take on time if not present?

This is messing up observability plugin, which assumes observedtimestamp as the default timestamp field

**To Reproduce**
https://github.com/opensearch-project/dashboards-observability/issues/245#issuecomment-1416250750

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]

**Additional context**

**Comment by graytaylor0** [comment]
Hi @derek-ho,

It is not clear to me what the expected behaviour/outcome is. Could you update that section of the issue to clarify? Where has the timestamp of 1970 been observed?

**Comment by derek-ho** [comment]
Sample document: 
```{
  "took": 0,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 34,
      "relation": "eq"
    },
    "max_score": 1,
    "hits": [
      {
        "_index": "otel-v1-logs-2023.06",
        "_id": "301iN4YB9XlfGxwRbxlY",
        "_score": 1,
        "_source": {
          "traceId": "",
          "spanId": "",
          "flags": 0,
          "time": "2023-02-09T18:14:02.883556488Z",
          "severityNumber": 9,
          "droppedAttributesCount": 0,
          "serviceName": "my-service",
          "body": "Service running on hostname: xxxxx with instance id: i-XXXXXXXXXX",
          "observedTime": "1970-01-01T00:00:00Z",
          "schemaUrl": "",
          "resource.attributes.service@instance@local_hostname": "XXXXXXXXXX.compute.internal",
          "resource.attributes.service@instance@local_ipv4": "172.24.160.99",
          "instrumentationScope.name": "my-service",
          "resource.attributes.service@version": "2.0.0+2f6c1d",
          "resource.attributes.telemetry@sdk@name": "opentelemetry",
          "resource.attributes.telemetry@sdk@language": "cpp",
          "resource.attributes.service@namespace": "pte",
          "resource.attributes.telemetry@sdk@version": "1.8.2",
          "resource.attributes.service@instance@id": "i-XXXXXXXXXX",
          "resource.attributes.service@name": "my-service",
          "resource.attributes.service@instance@public_hostname": "XXXXXXXXXX.amazonaws.com",
          "instrumentationScope.version": "2.0.0+2f6c1d"
        }
      }
    ]
  }
}```

**Comment by derek-ho** [comment]
@graytaylor0 details on how this was created can be found here: https://github.com/opensearch-project/dashboards-observability/issues/245#issuecomment-1416250750. I didn't want to paste a huge block of text. I also asked the initial reporter of the other issue to also record here how he got the document such as language/ingest method, etc.

**Comment by graytaylor0** [comment]
Thanks for sharing that. Looks like that field is populated by OpenTelemetry and not by data prepper (https://opentelemetry.io/docs/reference/specification/logs/data-model/#field-observedtimestamp). It might be helpful to share your OpenTelemetry collector configuration. Have you been able to confirm if the `observedTimestamp` field is set before it is sent to data prepper, and if so does it already contain a value of 1970?

**Comment by derek-ho** [comment]
@mrsparc can you add some more details?

**Comment by ArielGMachado** [comment]
This is an bug in the C++ OpenTelemetry (otel-cpp)  that will be handled by this issue https://github.com/open-telemetry/opentelemetry-cpp/issues/1984

**Comment by derek-ho** [comment]
@ArielGMachado we should be able to close this now, right? Seems like PR is merged

**Comment by ArielGMachado** [comment]
@derek-ho yes, this issue was not Data-prepper related and  PR to fix otel-cpp is merged.

**Comment by derek-ho** [comment]
Great, thanks so much @ArielGMachado , @graytaylor0 closing this now

**Comment by JannikBrand** [comment]
Hey, for me this is still a valid issue.

When sending data without `observedTimeUnixNano` and `timeUnixNano` [fields](https://github.com/open-telemetry/opentelemetry-proto/blob/2bd940b2b77c1ab57c27166af21384906da7bb2b/opentelemetry/proto/logs/v1/logs.proto#L139-L159) directly to Data Prepper, it will create Documents in OpenSearch including the `time` and `observedTime` field set to epoch 0 (Jan 1 1970).

Based on the spec of the [observedTime](https://opentelemetry.io/docs/specs/otel/logs/data-model/#field-observedtimestamp) field, it "is the time when OpenTelemetry’s code observed the event measured by the clock of the OpenTelemetry code", so Data Prepper should set it to the current time.

Based on the spec of the [time](https://opentelemetry.io/docs/specs/otel/logs/data-model/#field-timestamp) field, setting it to epoch 0 seems wrong. Either the field should be dropped (because it is optional) or set to the value of observedTime. The latter would make sense, since  the spec mentions: "Use Timestamp if it is present, otherwise use ObservedTimestamp".

---

Below some details to my test setup:
- DP version: 2.9.0

First, create a "otel-log-without-time.json" file, e.g.:

```
{
  "resourceLogs": [
    {
      "resource": {
        "attributes": [
          {
            "key": "service.name",
            "value": { "stringValue": "my-application" }
          }
        ],
        "droppedAttributesCount": 0
      },
      "scopeLogs": [
        {
          "scope": {
            "name": "scopeName",
            "version": "version1"
          },
          "logRecords": [
            {
              "severityNumber": 9,
              "severityText": "Info",
              "body": { "stringValue": "This is a log message" },
              "attributes": [],
              "droppedAttributesCount": 0,
              "traceId": "08040201000000000000000000000000",
              "spanId": "0102040800000000"
            }
          ],
          "schemaUrl": "foo"
        }
      ],
      "schemaUrl": "bar"
    }
  ]
}
```

Second, sent it via grpcurl to Data Prepper, e.g.:

`grpcurl -insecure -d @ < otel-log-without-time.json <dp_endpoint>:<dp_otel_log_port> opentelemetry.proto.collector.logs.v1.LogsService/Export`

Data Prepper log pipeline looks sth. like this (highlighting that the `proto_reflection_service` is enabled for grpcurl):

```
logs-pipeline:
  source:
    otel_logs_source:
      ssl: false
      proto_reflection_service: true

  buffer:
    bounded_blocking:
      buffer_size: 12800
      batch_size: 200
  processor:
  sink:
    - opensearch:
        hosts: [ "<opensearch_endpoint>" ]
        insecure: true
        username: <os_username>
        password: <os_user_password>
        index: logs-otel-v1-%{yyyy.MM.dd}
```

Resulting OpenSearch doc:

```
{
  "_index": "logs-otel-v1-2024.12.19",
  "_type": "_doc",
  "_id": "GB2n3pMB0Mc1_i72fE8Y",
  "_version": 1,
  "_score": null,
  "_source": {
    "traceId": "d3cd38d36d35d34d34d34d34d34d34d34d34d34d34d34d34",
    "spanId": "d35d36d38d3cd34d34d34d34",
    "severityText": "Info",
    "flags": 0,
    "time": "1970-01-01T00:00:00Z",
    "severityNumber": 9,
    "droppedAttributesCount": 0,
    "serviceName": "my-application",
    "body": "This is a log message",
    "observedTime": "1970-01-01T00:00:00Z",
    "schemaUrl": "bar",
    "instrumentationScope.name": "scopeName",
    "resource.attributes.service@name": "my-application",
    "instrumentationScope.version": "version1"
  },
  "fields": {
    "observedTime": [
      "1970-01-01T00:00:00.000Z"
    ],
    "time": [
      "1970-01-01T00:00:00.000Z"
    ]
  },
  "sort": [
    0
  ]
}
```

**Comment by amachado-pie** [comment]
Well, I'm not sure if DataPrepper should set these fields or if that is the responsibility of the SDK/collector that uses the OpenTelemetry instrumentation to create the trace/log event. 
The original issue in this thread was fixed in the `opentelemetry-cpp` project because that SDK was not going to assign a value to this field and thus exported the `ObservedTimestamp` with the default Unix epoch time.

If we think that this event was "collected" or "sent" by an OpenTelemetry instrumentation, I think it's the event source that is responsible for including the correct fields, like for example with the traceId.

But perhaps I suggest you create another issue or contact the DataPreper staff through channels like Slack to get a better opinion.

**Comment by JannikBrand** [comment]
> Well, I'm not sure if DataPrepper should set these fields or if that is the responsibility of the SDK/collector that uses the OpenTelemetry instrumentation to create the trace/log event.

The [spec](https://opentelemetry.io/docs/specs/otel/logs/data-model/#field-observedtimestamp) says: "is the time when OpenTelemetry’s code observed the event measured by the clock of the OpenTelemetry code". 
Since Data Prepper is the first instance in my experiment that contains OTel code, imo it makes sense that Data Prepper should set it.

I created => #5275 let's continue the discussion there (if needed.)
