### ISSUE TITLE
Support Proxies

### ISSUE THREAD

**Issue by matthewriedel-flux** [opensearch-project/data-prepper#300]
**Is your feature request related to a problem? Please describe.**
We, like thousands of other organisations, use proxies to filter outbound internet traffic. Without proxy support, `data-prepper` is unusable in our environment.

**Describe the solution you'd like**
Ideally, I could use `-Dhttp.proxyHost` and other Java proxy properties on the command line like most Java applications. Failing that, support via configuration (e.g., `data-prepper-config.yaml`) would be OK.

**Describe alternatives you've considered (Optional)**
There are no alternatives for our environment. I'm actually really surprised Amazon is recommending this tool without this basic feature. If this support exists, documentation for using it is nonexistant.

**Comment by dlvenable** [comment]
@matthewriedel-flux , Thank you for your feedback adding proxy support.

Yes, this is an important feature. Our current thinking is to make it available via the `data-prepper-config.yaml` file, as a configuration on the `opensearch` sink.

Here is some reasoning behind that approach:

* Not all network connections would go through the proxy. In particular, our peer forwarder is likely communicating with peers inside the same internal network and not going through a proxy. We don't want to force those connections through it.
* Using `http.proxyHost` would tie us into the `java.net` implementation. I don't believe we use that now, which is why it doesn't work. We would like to have a consistent interface for configuring and running Data Prepper. I would expect that whether a plugin uses `java.net` or not should be an internal detail which plugin authors can change without affecting existing configurations.

**Comment by matthewriedel-flux** [comment]
Thanks for the info, @dlvenable . That sounds like a reasonable approach. If you were to switch to the `java.net` implementation, the `http.nonProxyHosts` flag would probably allow the local communication you're describing.

But a configuration-based approach is a familiar path, though environment variables are more container-friendly.  But we're already mounting a configuration file in the container, so it's similar outcomes either way.

It will be hard to predict every type of environment this will deploy into, so if it was me, I'd try to provide flexibility of component placement. This means supporting proxied communication between any two endpoints.

**Comment by jianghancn** [comment]
Thanks @matthewriedel-flux @dlvenable 
I appreciate your great thoughts. As a developer who will extensively refactor Data Prepper's OpenSearch Sink plugin, I have considered your ideas. Accordingly, I am leaning toward the following approach: 

1. Having the proxy configurations in the data-prepper-config.yaml file in order to have one place managing all configurations. i.e. having a set of environment variable configurations could add confusion to both users and developers. 
2. To the configurations for OpenSearch Sink, we add support for two more parameters `proxyHost`  and `nonProxyHosts` to work together with existing `hosts` parameter to support proxy.
```
sink:
    - opensearch:
        ...
        hosts: [“localhost:9020”, “internal.mycorp.com:9020”, “opensearch.example.com:9020”]
        proxyHost:”proxy.searches.example.com:8000”
        nonProxyHosts:[“localhost:9020”, “internal.mycorp.com”]
```
In above example, we output events to three OpenSearch servers listed in the `hosts` parameter. However, ingestion will go directly to  “localhost:9020” and “internal.mycorp.com:9020”. At same time, ingestion will go through ”proxy.searches.example.com:8000” and then to  “opensearch.example.com:9020” in accordance to the values set for  `proxyHost`  and `nonProxyHosts`  and `hosts`

Do you have comments on the approach above? Thanks a lot.

**Comment by matthewriedel-flux** [comment]
Hi @jianghancn : I think that sounds reasonable. Thanks!
