### ISSUE TITLE
SENSITIVE logging should selectively censor arguments instead of censoring all arguments

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#3375]
**Is your feature request related to a problem? Please describe.**
Sensitive logging is performed to keep user data from being logged in data prepper. However, many of these sensitive logs censor more than they should, including important error messages. For example, the error message will be censored out here https://github.com/opensearch-project/data-prepper/blob/542b4517896f1f074a32575b9ee98fb737065ee2/data-prepper-plugins/failures-common/src/main/java/org/opensearch/dataprepper/plugins/dlq/s3/S3DlqWriter.java#L132

**Describe the solution you'd like**
A way to selectively censor arguments in the SENSITIVE logs by only censoring arguments in `[]` brackets. That way we can remove the brackets around arguments like error messages so they are not censored

**Describe alternatives you've considered (Optional)**

**Additional context**

**Comment by dlvenable** [comment]
The reason there is a `SENSITIVE` is because we don't know what fields are sensitive. The `EVENT` marker is a way to obscure only `Event` objects. But, in other cases, it is unclear which needs to be masked.

So I don't think we should try to guess by using brackets. However, I do think we should be sure to allow `Throwable` classes to not be masked. Then we can take this approach:

```
LOG.error(SENSITIVE, "Failed to write to S3 dlq: [{}] to S3",
                content, ex);
```

We hadn't finished this to support `EVENT` yet as seen in the TODO below. 

https://github.com/opensearch-project/data-prepper/blob/e341d7d3c9a55d37de5f512d4e1572ba8a881b0a/data-prepper-core/src/main/java/org/opensearch/dataprepper/logging/SensitiveArgumentMaskingConverter.java#L41-L48
