### ISSUE TITLE
Support parsing of xml fields in Events

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#4165]
**Is your feature request related to a problem? Please describe.**
As a user who sends XML in specific fields in Events to my Data Prepper pipelines, I would like to be able to parse the xml 

**Describe the solution you'd like**
A new processor to parse xml. 

**Describe alternatives you've considered (Optional)**

**Comment by dlvenable** [comment]
@graytaylor0 , I'm not sure what it means to "decrypt" XML. XML is just a format.

I think we could resolve this by making a new `parse_xml` processor. It would be similar to the `parse_json` and `parse_ion` processors. And it should be able to use the same framework since Jackson has an [XML parser](https://github.com/FasterXML/jackson-dataformat-xml).

```
- parse_xml:
     source: xmlstring
     pointer: /xml
```

The XML data can be encrypted in one of two ways. 1) The whole XML binary is encrypted; or 2) specific fields are encrypted as base64. Depending on how the data is encrypted, users could either: 1) Decrypt this before the parser. Or 2) decrypt specific fields after parsing it.

**Comment by cameronattard** [comment]
Related: https://github.com/opensearch-project/data-prepper/issues/4024
