### ISSUE TITLE
Support adding event fields with dynamic keys

### ISSUE THREAD

**Issue by oeyh** [opensearch-project/data-prepper#4175]
**Is your feature request related to a problem? Please describe.**
As a user, I'd like to use the value of some other field to construct the key of a new field. For example, if I have an event {"param_name": "cpu", "param_value": 50} and `param_name` field is dynamic across events, but I'd like to add a new field with the actual param name as key and param value as value. Current processors only support literal strings as keys.

**Describe the solution you'd like**
In `add_entries` processor, similar to `format` and `value_expression` options for specifying values, add `format_key` or `key_expression` option for specifying keys. 

**Describe alternatives you've considered (Optional)**
N/A

**Additional context**
N/A

**Comment by graytaylor0** [comment]
I think that we should consolidate and support format expressions in keys. We can keep the default behavior since we are able to validate if it's a format expression or not. So we could just have `key` and `metadata_key`, and they can either be

```
key: "staticKey"
```

or 

```
key: "my-%{/key_field}"
```

This covers all the cases and consolidates into one parameter. It is the exact same way we handle the sink `index` parameter

**Comment by graytaylor0** [comment]
Yes that was a typo! We should use the same syntax as our existing format expressions
