### ISSUE TITLE
Secure endpoint by default on http source

### ISSUE THREAD

**Issue by chenqi0805** [opensearch-project/data-prepper#461]
**Is your feature request related to a problem? Please describe.**
Currently the endpoint of http source is not secured by default

**Describe the solution you'd like**
* set default ssl to true
* Provide demo key and cert files for `ssl_certificate_file` and `ssl_key_file` as default. We could reuse `demo-data-prepper.crt` and `demo-data-prepper.key` in https://github.com/opensearch-project/data-prepper/tree/main/examples/demo
* For testing purpose, on the client side we could turn on tlsNoVerify: https://javadoc.io/doc/com.linecorp.armeria/armeria-javadoc/latest/com/linecorp/armeria/client/ClientFactoryBuilder.html

**Describe alternatives you've considered (Optional)**

**Additional context**

**Comment by dlvenable** [comment]
Because the `http` plugin must be turned on by users of Data Prepper, Data Prepper will not enable SSL or authentication by default. The user who turns on the plugin should also activate TLS and authentication. Instead, Data Prepper will use documentation and warnings to encourage users to configure it with TLS and authentication. See #521 .
