### ISSUE TITLE
flatten processor: option for keys wihout brackets

### ISSUE THREAD

**Issue by timo-mue** [opensearch-project/data-prepper#4616]
**Is your feature request related to a problem? Please describe.**
Currently the flatten processor adds empty squared brackets to the keys of list elements, even when the `remove_list_indices` option is set to `true`.  So something like
```json
{
  "key1": {
    "key2": [
      {
        "key3": "value1",
        "key4": "value2"
      },
      {
        "key3": "value3",
        "key4": "value4"
      }
    ]
  }
}
```
turns into
```json
{
  "key1.key2[].key3": ["value1", "value3"],
  "key1.key2[].key4": ["value2", "value4"]
}
```
When the mentioned option is set to `false` the brackets are needed to reference list indices but in this case they could easily be ommited. It would be nice if the keys would keep their original names and the output would be this instead:
```json
{
  "key1.key2.key3": ["value1", "value3"],
  "key1.key2.key4": ["value2", "value4"]
}
```
**Describe the solution you'd like**
Either remove the brackets from keys when `remove_list_indices` is set to `true`, or add an option (`original_key` or `remove_brackets`) that has the same effect when used together with `remove_list_indices` set to `true`.
**Additional context**
For some automated processes (e.g. creating mappings via index templates before writing documents) it could be valuable to retain the original key names.

**Comment by oeyh** [comment]
This is a reasonable ask and should be a small change. I will work on this.

**Comment by oeyh** [comment]
@timo-mue would you like contribute to Data Prepper and make the changes for this issue? Otherwise I can take it.

The related code is here:
https://github.com/opensearch-project/data-prepper/blob/ad92aa25b80a4951176f8c45c475dc6d704c2e75/data-prepper-plugins/flatten-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/flatten/FlattenProcessor.java#L118

The configs are set up in `FlattenProcessorConfig.java`

**Comment by oeyh** [comment]
There is a use case (https://github.com/opensearch-project/data-prepper/issues/3965) to keep the brackets after removing list indices, so we want to retain that option. 

We can add an option for removing the indices along with the brackets. Either:
```
remove_list_indices: true
remove_brackets: true
```
or
```
remove_list_indices_and_brackets: true
```

**Comment by timo-mue** [comment]
> @timo-mue would you like contribute to Data Prepper and make the changes for this issue? I can also help.

Sure, I will try to make the changes.

> We can add an option for removing the indices along with the brackets. Either through:
> 
> ```
> remove_list_indices: true
> remove_brackets: true
> ```

What would be the behavior for using `remove_list_indices: false` together with `remove_brackets: true`? Should that turn something like `"key1.key2[0].key3": "value1"` into `"key1.key20.key3": "value1"` or just get ignored?

**Comment by oeyh** [comment]
Thanks @timo-mue!

We should probably disallow that case by adding a validation (see an example [here](https://github.com/opensearch-project/data-prepper/blob/af7d1b54561a52ac13e7ba04d2b73a77cb0dc5cb/data-prepper-plugins/mutate-event-processors/src/main/java/org/opensearch/dataprepper/plugins/processor/mutateevent/AddEntryProcessorConfig.java#L75-L78) so that when `remove_list_indices` is false, `remove_brackets` cannot be true. 

Or, we use name `remove_list_indices_and_brackets` to bind them together.
