### ISSUE TITLE
Migrate Trace Analytics Plugins to Event Model

### ISSUE THREAD

**Issue by cmanning09** [opensearch-project/data-prepper#546]
Migrate existing trace plugins to event model. Trace analytics plugins should pass either a Record<Span> (or Record<Event> in the case of the service mapping plugin). This will eilminate excessive de/serialization between plugins

Plugins To be updated:
- Peer Forwarder
- otel source
- otel srv group prepper
- otel raw
- service map
- opensearch sink

related to #319 

**GitHub Issues**

* #600
* #604 
* #605 
* #606 
* #607 
* #608 
* #610
* #611
* #612
* #613
* #614
* #758

**Comment by chenqi0805** [comment]
Workflow:

1. Created a side branch for migration: https://github.com/opensearch-project/data-prepper/tree/maint/546-migrate-trace-analytics-plugin
2. Migrate OTelTraceSource, OTelTraceRawPrepper, OTelTraceGroupPrepper, ServiceMapStateful, mute broken e2e on demand.
3. Migrate PeerForwarder
4. Recover all e2e tests. Carry out performance test on `maint/546-migrate-trace-analytics-plugin` to verify improvement by comparing against `main`. Otherwise find the bottlenecks and fixes.
5. Merge `maint/546-migrate-trace-analytics-plugin` into `main`.
