### ISSUE TITLE
Checkstyle errors seem to be ignored

### ISSUE THREAD

**Issue by dblock** [opensearch-project/data-prepper#55]
**Describe the bug**
Noticed checkstyle errors ignored in https://github.com/opensearch-project/data-prepper/runs/2442523964#step:7:422, not sure it's on purpose.

```
Error: eckstyle] [ERROR] /home/runner/work/data-prepper/data-prepper/data-prepper-plugins/opensearch/src/main/java/com/amazon/dataprepper/plugins/sink/opensearch/IndexStateManagement.java:90: Line is longer than 140 characters (found 143). [LineLength]
```

**Comment by chenqi0805** [comment]
@dblock Thank you for the attention. Yes, we deliberately mute it: https://github.com/opensearch-project/data-prepper/blob/f7239fce5263430eb13d615f26621731f81d786e/data-prepper-plugins/opensearch/build.gradle#L146-L147 since data-prepper is on the client side and we are only using the OS gradle plugins for testing purpose.

**Comment by dblock** [comment]
But you probably do want to fix these? If not why not?

**Comment by dlvenable** [comment]
I removed the `build-tools` plugin from the `opensearch` Gradle project. Along with this, I was able to remove the `ignoreFailures` flag that were there previously.
