### ISSUE TITLE
LogstashConfigConverter: converting index with a date-time pattern

### ISSUE THREAD

**Issue by jianghancn** [opensearch-project/data-prepper#854]
**Is your feature request related to a problem? Please describe.**
As the RFC #755, Data-Prepper not supports index names with a date-time pattern as a suffix. 
Logstash also supports a date-time pattern in index. However, Logstash doesn't support the date-time pattern conversion. 

**Describe the solution you'd like**
We should have Logstash Config Converter to be able to convert Logtash's version of index with data a time pattern to Data Prepper's version of index with a data-time pattern. 

One catch: 
Logstash's date time patten uses Joda time [formatter](https://www.joda.org/joda-time/key_format.html). 
Data-Prepper date time pattern uses Java Time [DateTimeFormatter](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html)

**Describe alternatives you've considered (Optional)**
NA
**Additional context**
NA

**Comment by sshivanii** [comment]
Based on my research on the [Joda time formatter](https://www.joda.org/joda-time/key_format.html) and [Java 8 DateTime formatter](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html), I found some similarities between the two date-time patterns. 

For further investigation, I performed some tests using the Data Prepper jar, with a random String Source, Grok Processor and an OpenSearch Sink writing logs to different valid Joda and Java 8 date-time patterns as `index` in `basic-grok-pipeline.yaml`. This was to observe if Joda date-time pattern would throw an exception.
```
grok-pipeline:
  source:
    random:
  prepper:
    - grok:
        match:
          log: [ "%{COMMONAPACHELOG}" ]
  sink:
    - opensearch:
        hosts: [ "https://localhost:9200" ]
        username: admin
        password: admin
        index: "log-index-%{+YYYY.MM.dd.}"
```
Here are my findings:

* The sink successfully writes to index `log-index-%{yyyy.MM.dd}` which is in Java 8 date format.
* The sink successfully writes to `my-index-name-%{yyyy.MM.dd.HH}`, Java 8 date-time format.
* The sink successfully writes to index `logstash-index-%{+yyyy.MM.dd}` and `index-%{+YYYY.MM.dd}`, Joda date formats. However, it prepends a `+` sign. For instance, in the OpenSearch dashboard, the index created is `logstash-index-+2022.02.08.` One thing to note here is that the converted date is correct each time.
* The sink also writes successfully to index `test-logstash-%{+YYYY.MM.dd}`, seen in Logstash documentation, with the correct date but the `+` sign too.

This is because the Pattern letters in the two formats which we want to use as suffix for date-time format are the same.
One major difference I initially found was `YYYY` for year in Joda vs `yyyy` in Java 8 time, however Joda also has `yyyy` as year.

Since the OpenSearch sink is reading the two formats and converting them correctly to date-time except the added `+` sign, I believe there's no pressing need for this pattern conversion.

I'd like to hear more thoughts on this!

**Comment by dlvenable** [comment]
There are subtle differences between the different year formats.

The week-year is different from a calendar year. For example Dec 31, 2021 (calendar year) is actually in the 2022 week-year because it is in the same week as Jan 1, 2022.

Supporting week-years is important. Many users index based on week-year and day of week.

So the Logstash configuration converter will need to convert `x` (Joda's week-year) to `Y` (Java 8's week-based-year).
