### ISSUE TITLE
[BUG] Fix remaining failing unit tests on Windows

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#970]
**Describe the bug**
Some unit tests are not compatible with Windows, and causes the overall build to fail

**To Reproduce**
Run `./gradlew build` for Data Prepper on a Windows computer

**Expected behavior**
The build should succeed.

**Environment (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
Some of the failed tests were fixed in this PR #968

**Comment by jzonthemtn** [comment]
Hi! I looked into this and I think the underlying issue is how `Path` handles a path with a leading slash that Windows gives, e.g. `/C:/some/directory`. This causes the `InvalidPathException` that shows up in the unit tests on Windows:

`Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/some/directory`

`File` is able to handle the "system-dependent prefix string" ([javadoc](https://docs.oracle.com/javase/7/docs/api/java/io/File.html#toPath())) and so changing from `Path.of()` to `File.toPath()` lets it work on Windows and non-Windows.

I tested the build on Windows 11 and Ubuntu 20.04. Please take a look at the PR and let me know if there's any issues!

**Comment by dlvenable** [comment]
Thanks @jzonthemtn for resolving the Windows build issues.
